### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by Divyarajsinh1312**
Clear unnecessary comments

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)

Demonstrate the code is solid. If not, please add `WIP:` in its title.

### Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### Self Check before Merge

Please check all items below before review.

-   [ ] Corresponding issues are created/updated or not needed
-   [ ] Docs are updated/provided or not needed
-   [ ] Examples are updated/provided or not needed
-   [ ] TypeScript definitions are updated/provided or not needed
-   [ ] Tests are updated/provided or not needed
-   [ ] Changesets are provided or not needed

### CODE REVIEW

**Comment by Divyarajsinh1312** [comment]
Please add hacktoberfest-accepted label

**Review by omeraplak — APPROVED** [review]

**Comment by Divyarajsinh1312** [comment]
Please add hacktoberfest-accepted label

**Comment by Divyarajsinh1312** [comment]
Please can you tell me when swag related mail is out

**Comment by omeraplak** [comment]
Hey,
Can you reach us on our [Discord](http://discord.gg/refine) server?

**Comment by Divyarajsinh1312** [comment]
I join your discord now?

**Comment by Divyarajsinh1312** [comment]
Hello,
I join your discord now?

**Pull request merged**
