### PR TITLE
[FEAT] Add support for AND/OR conditional filters 

### LINKED ISSUE #1627: [FEAT] Add support for `and` conditional filter
**Is your feature request related to a problem? Please describe.**
Now that the conditional or filter is available (see https://github.com/pankod/refine/issues/1417) it would be cool to have a complementary `and` filter such that the following query becomes possible:

```sql
OR(
  AND(
    {title} == "The Great Divide",
    {age} < 10,
  ),
  AND(
    {title} == "The New Era",
    {age} < 20,
  )
)
```

This would allow to construct complex filters for different situations. Currently it's only possible to do the following:
```sql
AND(
  OR(
    {title} == "The Great Divide",
    {title} == "The New Era",
  ),
  OR(
    {age} < 10,
    {age} < 20,
  )
)
```

One can notice however that these are not the same and the condition for the age is now not tied to the specific titles and in this example `{age} < 10` actually being useless since `{age} < 20` already satisfies it.

**Describe the solution you'd like**
An additional `and` filter based on the same principle as the `or` filter.

**Describe alternatives you've considered**
The top-level implicit `AND` that already exists is good but does limit the queries we can construct if we need to narrow down results individually.

### PR DESCRIPTION
**Pull request by Smartmind12**
Closes #1627

### CODE REVIEW

**Comment by alicanerdurmaz** [comment]
Hi @Smartmind12 Thanks for the PR 👊 

Unfortunately, adding only type definitions will not be enough to use this feature. We must implement `AND` logic it in the supporting dataProviders. For example: [nestjsx-crud](https://github.com/pankod/refine/blob/next/packages/nestjsx-crud/src/index.ts#L100)

**Comment by Smartmind12** [comment]
> Hi @Smartmind12 Thanks for the PR 👊
> 
> Unfortunately, adding only type definitions will not be enough to use this feature. We must implement `AND` logic it in the supporting dataProviders. For example: [nestjsx-crud](https://github.com/pankod/refine/blob/next/packages/nestjsx-crud/src/index.ts#L100) is a good option to add this feature.

Hey sure will work on it and update the same!

**Comment by Smartmind12** [comment]
> Hi @Smartmind12 Thanks for the PR 👊
> 
> Unfortunately, adding only type definitions will not be enough to use this feature. We must implement `AND` logic it in the supporting dataProviders. For example: [nestjsx-crud](https://github.com/pankod/refine/blob/next/packages/nestjsx-crud/src/index.ts#L100) is a good option to add this feature.

I have made the additional changes kindly review!

**Comment by yildirayunlu** [comment]
Hi @Smartmind12, I made a review again. But I think it doesn't solve the problem in the issue.
You can test it with the example [here](https://github.com/pankod/refine/tree/next/examples/dataProvider/nestjsxCrud).

**Pull request closed without merging**
