### PR TITLE
test: update async timeouts globally

### PR DESCRIPTION
**Pull request by aliemir**
Fixing the random failing issue of tests on CI.

### Test plan (required)

Still on draft

### Self Check before Merge

Please check all items below before review.

-   [x] Corresponding issues are created/updated or not needed
-   [x] Docs are updated/provided or not needed
-   [x] Examples are updated/provided or not needed
-   [x] TypeScript definitions are updated/provided or not needed
-   [x] Tests are updated/provided or not needed
-   [x] Changesets are provided or not needed

### CODE REVIEW

**Comment by aliemir** [comment]
I'll mark this as ready after 6 consecutive successful runs. This was the first.

**Comment by aliemir** [comment]
:(

**Comment by omeraplak** [comment]
> :(

image

**Comment by aliemir** [comment]
I set up an action with 10 jobs and every job runs the tests twice. Currently total consecutive success count is 17. If all succeed, it will be 38.

**Comment by aliemir** [comment]
I'm not super confident to say they won't fail again but at least we know we've fixed some smells and wrong structured tests. There may be two or three more suits might fail but we can fix those when we see them.

**Review by omeraplak — APPROVED** [review]

**Pull request merged**
